### ISSUE TITLE
[Bug] 2.3.0 BETA Bug list:

### ISSUE THREAD

**Issue by BoxDevelopment** [ToberoCat/ImprovedFactions#265]
Bug with power regeneration:

At the moment Power does not regenerate for factions automatically 

My config is 

```
  power-management:
    base-member-constant: 50 # Note that this is indeed a constant - Therefore changing this might cause balancing issues on your server
    accumulation-rate: # Configure how often faction powers will be accumulated. Increasing it to be too frequent might cause database bottlenecks
      unit: MINUTES # The time unit this value will be interpreted as. Some more common possibilities are: SECONDS, MINUTES, HOURS and DAYS
      value: 30

    # Configure how long a player counts as active.
    inactive:
      unit: DAYS # The time unit this value will be interpreted as. Some more common possibilities are: SECONDS, MINUTES, HOURS and DAYS
      value: 7
    base-accumulation: 0 # Set how much power a faction gets even when no members are online
    accumulation-multiplier: 10 # A value that will get applied at the end
    # This is a constant responsible for rewarding when multiple people of a faction are online simultaneous.
    # It's used in an exponential growth function, so don't make it too big
    accumulation-active-exponent: 2
    # This is a constant responsible for penalizing inactive people of a faction are online simultaneous.
    # It's used in an exponential growth function, so don't make it too big
    accumulation-inactive-multiplier: 2
    base-claim-power-cost: 5 # The base power cost for claiming a chunk
    claim-power-cost-growth: 1.1 # exponentially grows the power cost of claims.
    # This is the amount of power each claim costs a faction. Note that this will be withdrawn even when the faction is offline,
    # making it possible for them getting vulnerable while being offline
    claim-power-keep: 0
    player-death-cost: 5 # How much power the faction loses when a player dies
    allow-overclaiming: true # If set to true, 
    ```
